name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install
      run: |
        npm i

    - name: Test
      run: |
        npm run test
